import 'package:alalamia_admin/core/config/app_config_model.dart';
import 'package:alalamia_admin/core/router/app_router.gr.dart';
import 'package:auto_route/auto_route.dart';

/// Application router configuration using the auto_route package for navigation management
/// Handles all route definitions, navigation structure, and page transitions throughout the app
/// Route names are automatically generated by replacing 'View' suffix with 'Route' for consistency
@AutoRouterConfig(replaceInRouteName: 'View,Route')
class AppRouter extends RootStackRouter {
  /// Singleton instance ensuring single router throughout the application lifecycle
  static final AppRouter instance = AppRouter._();

  /// Private constructor implementing singleton design pattern
  AppRouter._();

  /// Builds the complete navigation structure for the entire application
  /// Defines route hierarchy from splash screen through authenticated user flows
  @override
  List<AutoRoute> get routes => [
    /// Application entry point - displays while checking authentication status
    AutoRoute(page: SplashRoute.page, initial: true),

    /// User authentication flow for login and credential verification
    AutoRoute(page: SignInRoute.page),

    /// Main application shell containing bottom navigation and primary user interface
    /// State preservation controlled by configuration to optimize user experience
    AutoRoute(
      maintainState: AppConfigModel.maintainStateMainPages,
      page: MainRoute.page,
      children: [
        /// Business analytics dashboard showing key performance metrics and insights
        AutoRoute(page: StatisticsRoute.page),

        /// Order management interface - primary landing page for authenticated users
        AutoRoute(page: OrdersRoute.page, initial: true),

        /// Application settings and user preference configuration panel
        AutoRoute(page: SettingsRoute.page),
      ],
    ),

    /// Detailed order information screen for viewing and managing individual orders
    AutoRoute(page: OrderDetailsRoute.page),
  ];
}
